src/Feature/Accounts/code/Models/EditProfile.cs
namespace Sitecore.Feature.Accounts.Models
{
  using System.Collections.Generic;
  using System.ComponentModel.DataAnnotations;
  using Sitecore.Feature.Accounts.Texts;

  public class EditProfile
  {
    [Display(Name = nameof(Captions.FirstName), ResourceType = typeof(Captions))]
    public string FirstName { get; set; }

    [Display(Name = nameof(Captions.LastName), ResourceType = typeof(Captions))]
    public string LastName { get; set; }

    [Display(Name = nameof(Captions.PhoneNumber), ResourceType = typeof(Captions))]
    [RegularExpression(@"^\+?\d*(\(\d+\)-?)?\d+(-?\d+)+$", ErrorMessageResourceName = nameof(Errors.PhoneNumberFormat), ErrorMessageResourceType = typeof(Errors))]
    [MaxLength(20, ErrorMessageResourceName = nameof(Errors.MaxLength), ErrorMessageResourceType = typeof(Errors))]
    public string PhoneNumber { get; set; }

    [Display(Name = nameof(Captions.Interests), ResourceType = typeof(Captions))]
    public string Interest { get; set; }
    
    public IEnumerable<string> InterestTypes { get; set; }
  }
}

src/Feature/Accounts/code/Models/InfoMessage.cs
namespace Sitecore.Feature.Accounts.Models
{
  public class InfoMessage
  {
    public InfoMessage()
    {
    }

    public InfoMessage(string message): this(message, MessageType.Info)
    {
    }

    public InfoMessage(string message, MessageType messageType)
    {
      this.Message = message;
      this.Type = messageType;
    }

    public string Message { get; set; }

    public MessageType Type { get; set; }

    public enum MessageType
    {
      Info,Success,Warning,Error
    }
  }
}

src/Feature/Accounts/code/Controllers/AccountsController.cs
namespace Sitecore.Feature.Accounts.Controllers
{
  using System;
  using System.Web.Mvc;
  using System.Web.Security;
  using Sitecore;
  using Sitecore.Diagnostics;
  using Sitecore.Feature.Accounts.Attributes;
  using Sitecore.Feature.Accounts.Models;
  using Sitecore.Feature.Accounts.Repositories;
  using Sitecore.Feature.Accounts.Services;
  using Sitecore.Feature.Accounts.Texts;
  using Sitecore.Foundation.SitecoreExtensions.Extensions;

  public class AccountsController : Controller
  {
    private readonly IAccountRepository accountRepository;
    private readonly INotificationService notificationService;
    private readonly IAccountsSettingsService accountsSettingsService;
    private readonly IUserProfileService userProfileService;
    private readonly IContactProfileService contactProfileService;

    public AccountsController() : this(new AccountRepository(new AccountTrackerService(new AccountsSettingsService())), new NotificationService(new AccountsSettingsService()), new AccountsSettingsService(), new UserProfileService(), new ContactProfileService())
    {
    }

    public AccountsController(IAccountRepository accountRepository, INotificationService notificationService, IAccountsSettingsService accountsSettingsService, IUserProfileService userProfileService, IContactProfileService contactProfileService)
    {
      this.accountRepository = accountRepository;
      this.notificationService = notificationService;
      this.accountsSettingsService = accountsSettingsService;
      this.userProfileService = userProfileService;
      this.contactProfileService = contactProfileService;
    }

    [HttpGet]
    [AccountsRedirectAuthenticated]
    public ActionResult Register()
    {
      return this.View();
    }

    [HttpPost]
    [ValidateModel]
    [AccountsRedirectAuthenticated]
    public ActionResult Register(RegistrationInfo registrationInfo)
    {
      if (this.accountRepository.Exists(registrationInfo.Email))
      {
        this.ModelState.AddModelError(nameof(registrationInfo.Email), Errors.UserAlreadyExists);

        return this.View(registrationInfo);
      }

      try
      {
        this.accountRepository.RegisterUser(registrationInfo.Email, registrationInfo.Password, this.userProfileService.GetUserDefaultProfileId());
        if (this.contactProfileService != null)
        {
          this.contactProfileService.SetPreferredEmail(registrationInfo.Email);
        }

        var link = this.accountsSettingsService.GetPageLinkOrDefault(Context.Item, Templates.AccountsSettings.Fields.AfterLoginPage, Context.Site.GetRootItem());
        return this.Redirect(link);
      }
      catch (MembershipCreateUserException ex)
      {
        Log.Error($"Can't create user with {registrationInfo.Email}", ex, this);
        this.ModelState.AddModelError(nameof(registrationInfo.Email), ex.Message);

        return this.View(registrationInfo);
      }
    }

    [HttpGet]
    [AccountsRedirectAuthenticated]
    public ActionResult Login()
    {
      return this.View();
    }

    [HttpPost]
    [ValidateModel]
    public ActionResult Login(LoginInfo loginInfo)
    {
      return this.Login(loginInfo, redirectUrl => new RedirectResult(redirectUrl));
    }

    protected virtual ActionResult Login(LoginInfo loginInfo, Func<string, ActionResult> redirectAction)
    {
      var result = this.accountRepository.Login(loginInfo.Email, loginInfo.Password);
      if (result)
      {
        var redirectUrl = loginInfo.ReturnUrl;
        if (string.IsNullOrEmpty(redirectUrl))
        {
          redirectUrl = this.accountsSettingsService.GetPageLinkOrDefault(Context.Item, Templates.AccountsSettings.Fields.AfterLoginPage, Context.Site.GetRootItem());
        }

        return redirectAction(redirectUrl);
      }

      this.ModelState.AddModelError("invalidCredentials", "Username or password is not valid.");

      return this.View(loginInfo);
    }

    [HttpPost]
    [ValidateModel]
    public ActionResult LoginDialog(LoginInfo loginInfo)
    {
      return this.Login(loginInfo, redirectUrl => this.Json(new LoginResult
      {
        RedirectUrl = redirectUrl
      }));
    }

    [HttpPost]
    public ActionResult Logout()
    {
      this.accountRepository.Logout();

      return this.Redirect(Context.Site.GetRootItem().Url());
    }

    [HttpGet]
    [AccountsRedirectAuthenticated]
    public ActionResult ForgotPassword()
    {
      return this.View();
    }

    [HttpPost]
    [ValidateModel]
    [AccountsRedirectAuthenticated]
    public ActionResult ForgotPassword(PasswordResetInfo model)
    {
      if (!this.accountRepository.Exists(model.Email))
      {
        this.ModelState.AddModelError(nameof(model.Email), Errors.UserDoesNotExist);

        return this.View(model);
      }

      try
      {
        var newPassword = this.accountRepository.RestorePassword(model.Email);
        this.notificationService.SendPassword(model.Email, newPassword);
        return this.View("InfoMessage", new InfoMessage(Captions.ResetPasswordSuccess));
      }
      catch (Exception ex)
      {
        Log.Error($"Can't reset password for user {model.Email}", ex, this);
        this.ModelState.AddModelError(nameof(model.Email), ex.Message);

        return this.View(model);
      }
    }

    [HttpGet]
    [RedirectUnauthenticated]
    public ActionResult EditProfile()
    {
      if (!Context.PageMode.IsNormal)
      {
        return this.View(this.userProfileService.GetEmptyProfile());
      }

      if (this.userProfileService.GetUserDefaultProfileId() != Context.User.Profile.ProfileItemId)
      {
        return this.View("InfoMessage", new InfoMessage(Errors.ProfileMismatch, InfoMessage.MessageType.Error));
      }

      var profile = this.userProfileService.GetProfile(Context.User.Profile);

      return this.View(profile);
    }

    [HttpPost]
    [RedirectUnauthenticated]
    public virtual ActionResult EditProfile(EditProfile profile)
    {
      if (this.userProfileService.GetUserDefaultProfileId() != Context.User.Profile.ProfileItemId)
      {
        return this.View("InfoMessage", new InfoMessage(Errors.ProfileMismatch, InfoMessage.MessageType.Error));
      }

      if (!this.userProfileService.ValidateProfile(profile, this.ModelState))
      {
        profile.InterestTypes = this.userProfileService.GetInterests();
        return this.View(profile);
      }

      this.userProfileService.SetProfile(Context.User.Profile, profile);
      if (this.contactProfileService != null)
      {
        this.contactProfileService.SetProfile(profile);
      }

      Session["EditProfileMessage"] = new InfoMessage(Captions.EditProfileSuccess);
      return this.Redirect(Request.RawUrl);
    }
  }
}

src/Feature/Accounts/code/Views/Accounts/AccountsDetails.cshtml
<form>
  <div class="form-group">
    <label for="detailsEmail">E-mail</label>
    <input type="email" class="form-control" id="detailsEmail" placeholder="E-mail">
  </div>
  <div class="form-group">
    <label for="detailsName">Name</label>
    <input type="email" class="form-control" id="detailsName" placeholder="Name">
  </div>
  <div class="form-group">
    <label for="detailsPassword">Password</label>
    <input type="password" class="form-control" id="detailsPassword" placeholder="Password">
  </div>
  <div class="form-group">
    <label for="detailsPassword">Confirm Password</label>
    <input type="password" class="form-control" id="detailsConfirmPassword" placeholder="Confirm Password">
  </div>
  <button type="submit" class="btn btn-default">Update</button>
</form>

src/Feature/Accounts/code/Views/Accounts/AccountsMenu.cshtml
@using Sitecore.Feature.Accounts
@using Sitecore.Feature.Accounts.Models
@using Sitecore.Feature.Accounts.Services
@using Sitecore.Feature.Accounts.Texts
@model Sitecore.Mvc.Presentation.RenderingModel
<li class="dropdown">
	<a href="#" class="dropdown-toggle" data-toggle="dropdown">
		<i class="fa fa-user"></i>
	</a>
	<ul class="dropdown-menu">
		@if (!(Sitecore.Context.IsLoggedIn && Sitecore.Context.PageMode.IsNormal))
		{
		<li>
			<a href="#" data-toggle="modal" data-target="#loginModal">Login</a>
		</li>
		<li>
			<a href="@AccountsSettingsService.Instance.GetPageLink(Model.Item, Templates.AccountsSettings.Fields.RegisterPage)">Register</a>
		</li>
		}
		else
		{
		<li>
			<div class="dropdown-item-body">
				<dl class="dl-horizontal">
					@if (!string.IsNullOrWhiteSpace(Sitecore.Context.User.Profile.FullName))
					{
					<dt>@Captions.Name</dt>
					<dd>@Sitecore.Context.User.Profile.FullName</dd>
					}
					<dt>@Captions.Email</dt>
					<dd>@Sitecore.Context.User.Profile.Email</dd>
				</dl>
			</div>
		</li>
		<li>
			<a href="@AccountsSettingsService.Instance.GetPageLink(Model.Item, Templates.AccountsSettings.Fields.AccountsDetailsPage)">@Captions.EditDetails</a>
		</li>
		<li>
			@using (Html.BeginForm("Logout", "Accounts", FormMethod.Post))
			{
			<input type="submit" value="@Captions.Logout" />
			}
		</li>
		}
	</ul>
</li>
<!-- Login Modal -->
<div class="modal fade" id="loginModal" tabindex="-1" role="dialog">
	<div class="modal-dialog" role="document">
		<form class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
				<h4 class="modal-title" id="myModalLabel">@Captions.Login</h4>
			</div>
			@Html.Partial("../Accounts/LoginDialog", new LoginInfo())
		</form>
	</div>
</div>

src/Feature/Accounts/code/Views/Accounts/EditProfile.cshtml
@using System.Web.Mvc.Html
@using Sitecore.Analytics.Tracking
@using Sitecore.Feature.Accounts.Models
@using Sitecore.Feature.Accounts.Texts
@using Sitecore.Foundation.SitecoreExtensions.Extensions
@using Sitecore.Foundation.SitecoreExtensions.HtmlHelpers
@using Sitecore.Mvc.Configuration
@model Sitecore.Feature.Accounts.Models.EditProfile

@using (Html.BeginRouteForm(MvcSettings.SitecoreRouteName, FormMethod.Post))
{
    var info = Session.GetAndRemove("EditProfileMessage") as InfoMessage;
    if (info != null)
    {
        Html.RenderPartial("InfoMessage", info);
    }
    <div class="form-group @Html.ValidationErrorFor(x => x.FirstName, "has-error")">
        @Html.LabelFor(x => x.FirstName, new {@class = "control-label"})

        @Html.ValidationMessageFor(x => x.FirstName, "", new {@class = "help-block"})

        @Html.TextBoxFor(x => x.FirstName, new {@class = "form-control", id = "firstName"})
    </div>

    <div class="form-group @Html.ValidationErrorFor(x => x.LastName, "has-error")">
        @Html.LabelFor(x => x.LastName, new {@class = "control-label"})

        @Html.ValidationMessageFor(x => x.LastName, "", new {@class = "help-block"})

        @Html.TextBoxFor(x => x.LastName, new {@class = "form-control", id = "lastName"})
    </div>

    <div class="form-group @Html.ValidationErrorFor(x => x.PhoneNumber, "has-error")">
        @Html.LabelFor(x => x.PhoneNumber, new {@class = "control-label"})

        @Html.ValidationMessageFor(x => x.PhoneNumber, "", new {@class = "help-block"})

        @Html.TextBoxFor(x => x.PhoneNumber, new {@class = "form-control", id = "phoneNumber"})
    </div>

    <div class="form-group @Html.ValidationErrorFor(x => x.Interest, "has-error")">
        @Html.LabelFor(x => x.Interest, new {@class = "control-label"})

        @Html.ValidationMessageFor(x => x.Interest, "", new {@class = "help-block"})

        @Html.DropDownListFor(x=>x.Interest,new SelectList(Model.InterestTypes),"", new { @class ="form-control", id = "interests"})
    </div>

    <input type="submit" class="btn btn-default" value="@Captions.Update" />
}

src/Feature/Accounts/code/Views/Accounts/ForgotPassword.cshtml
@using Sitecore.Feature.Accounts.Texts
@using Sitecore.Foundation.SitecoreExtensions.HtmlHelpers
@using Sitecore.Mvc.Configuration
@model Sitecore.Feature.Accounts.Models.PasswordResetInfo

@using (Html.BeginRouteForm(MvcSettings.SitecoreRouteName, FormMethod.Post))
{
  @Html.Sitecore().FormHandler()
  <div class="form-group @Html.ValidationErrorFor(x => x.Email, "has-error")">
    @Html.LabelFor(x => x.Email, new
    {
      @class = "control-label"
    })

    @Html.ValidationMessageFor(x => x.Email, "", new
    {
      @class = "help-block"
    })

    @Html.TextBoxFor(x => x.Email, new
    {
      @class = "form-control",
      id = "registerEmail"
    })
  </div>

  <input type="submit" class="btn btn-default" value="@Captions.ResetPassword"/>
  <div class="help-block">@Captions.ResetPasswordInfo</div>
}

src/Feature/Accounts/code/Views/Accounts/InfoMessage.cshtml
@using Sitecore.Feature.Accounts.Models
@model Sitecore.Feature.Accounts.Models.InfoMessage
@{
    var alerts = new Dictionary<InfoMessage.MessageType, string>()
    {
        [InfoMessage.MessageType.Info] = "alert-info",
        [InfoMessage.MessageType.Success] = "alert-success",
        [InfoMessage.MessageType.Warning] = "alert-warning",
        [InfoMessage.MessageType.Error] = "alert-danger",

    };
}
@if (Model != null)
{
    <div class="alert @alerts[Model.Type]">@Model.Message</div>
}

src/Feature/Accounts/code/Views/Accounts/Login.cshtml
@using Sitecore.Feature.Accounts
@using Sitecore.Feature.Accounts.Services
@using Sitecore.Feature.Accounts.Texts
@using Sitecore.Foundation.SitecoreExtensions.HtmlHelpers
@using Sitecore.Mvc
@model Sitecore.Feature.Accounts.Models.LoginInfo

@using (Html.BeginRouteForm(Sitecore.Mvc.Configuration.MvcSettings.SitecoreRouteName, FormMethod.Post))
{
@Html.Sitecore().FormHandler()
@Html.ValidationSummary(true)
<div class="form-group @Html.ValidationErrorFor(x=>x.Email, "has-error")">
    @Html.LabelFor(x => x.Email, new { @class = "control-label" })
    @Html.ValidationMessageFor(x => x.Email, "", new { @class = "help-block" })
    @Html.ValidationMessage("invalidCredentials", new { @class = "help-block" })
    @Html.TextBoxFor(x => x.Email, new { @class = "form-control", id = "loginEmail", @placeholder = "E-mail" })
</div>
<div class="form-group @Html.ValidationErrorFor(x=>x.Password, "has-error")">
    @Html.LabelFor(x => x.Password, new { @class = "control-label" })
    @Html.ValidationMessageFor(x => x.Password, "", new { @class = "help-block" })
    @Html.PasswordFor(x => x.Password, new { @class = "form-control", id = "loginPassword", @placeholder = "Password" })
</div>
<input type="submit" class="btn btn-default" value="@Captions.Login" />
<a href="@AccountsSettingsService.Instance.GetPageLink(Sitecore.Context.Item, Templates.AccountsSettings.Fields.ForgotPasswordPage)" class="btn btn-link">@Captions.ForgotYourPassword</a>
}

src/Feature/Accounts/code/Views/Accounts/LoginDialog.cshtml
@using Sitecore.Feature.Accounts
@using Sitecore.Feature.Accounts.Services
@using Sitecore.Feature.Accounts.Texts
@using Sitecore.Foundation.SitecoreExtensions.HtmlHelpers
@using Sitecore.Mvc
@model Sitecore.Feature.Accounts.Models.LoginInfo

<div class="modal-body">
    <div class="form-group @Html.ValidationErrorFor(x=>x.Email, "has-error")">
        @Html.LabelFor(x => x.Email, new { @class = "control-label" })
        @Html.ValidationMessageFor(x => x.Email, "", new { @class = "help-block" })
        @Html.ValidationMessage("invalidCredentials", new { @class = "help-block" })
        @Html.TextBoxFor(x => x.Email, new { @class = "form-control", id = "popupLoginEmail", @placeholder = "E-mail" })
    </div>
    <div class="form-group @Html.ValidationErrorFor(x=>x.Password, "has-error")">
        @Html.LabelFor(x => x.Password, new { @class = "control-label" })
        @Html.ValidationMessageFor(x => x.Password, "", new { @class = "help-block" })
        @Html.PasswordFor(x => x.Password, new { @class = "form-control", id = "popupLoginPassword", @placeholder = "Password" })
    </div>
    <a href="@AccountsSettingsService.Instance.GetPageLink(Sitecore.Context.Item, Templates.AccountsSettings.Fields.ForgotPasswordPage)" class="btn btn-link">@Captions.ForgotYourPassword</a>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">@Captions.Cancel</button>
    <button type="button" class="btn btn-primary" onclick="login('loginModal')">@Captions.Login</button>
</div>

src/Feature/Accounts/code/Views/Accounts/Register.cshtml
@using Sitecore.Feature.Accounts.Texts
@using Sitecore.Foundation.SitecoreExtensions.HtmlHelpers
@using Sitecore.Mvc.Configuration
@model Sitecore.Feature.Accounts.Models.RegistrationInfo

@using (Html.BeginRouteForm(MvcSettings.SitecoreRouteName, FormMethod.Post))
{
  @Html.Sitecore().FormHandler()
  <div class="form-group @Html.ValidationErrorFor(x => x.Email, "has-error")">
    @Html.LabelFor(x => x.Email, new
    {
      @class = "control-label"
    })

    @Html.ValidationMessageFor(x => x.Email, "", new
    {
      @class = "help-block"
    })

    @Html.TextBoxFor(x => x.Email, new
    {
      @class = "form-control",
      id = "registerEmail"
    })
  </div>

  <div class="form-group @Html.ValidationErrorFor(x => x.Password, "has-error")">
    @Html.LabelFor(x => x.Password, new
    {
      @class = "control-label"
    })

    @Html.ValidationMessageFor(x => x.Password, "", new
    {
      @class = "help-block"
    })

    @Html.PasswordFor(x => x.Password, new
    {
      @class = "form-control",
      id = "registerPassword"
    })
  </div>

  <div class="form-group @Html.ValidationErrorFor(x => x.ConfirmPassword, "has-error")">
    @Html.LabelFor(x => x.ConfirmPassword, new
    {
      @class = "control-label"
    })

    @Html.ValidationMessageFor(x => x.ConfirmPassword, "", new
    {
      @class = "help-block"
    })

    @Html.PasswordFor(x => x.ConfirmPassword, new
    {
      @class = "form-control",
      id = "registerConfirmPassword"
    })
  </div>

  <input type="submit" class="btn btn-default" value="@Captions.Register"/>
}